version: "3.7"

#################################################################
#                            DEFAULTS                           #
#################################################################
x-defaults: &defaults
  restart: always
  extra_hosts:
    - "host.docker.internal:host-gateway"
  logging:
    driver: syslog
    options:
      tag: "{{ 'docker-{{.Name}}' }}"

#################################################################
#                            SERVICES                           #
#################################################################
services:
  # =========================
  # =         PROXY         =
  # =========================
  traefik:
    <<: *defaults
    image: traefik:latest
    container_name: traefik
    command:
      # - "--log.level=DEBUG"
      - "--providers.file.directory=/conf"
      - "--providers.file.watch=true"
      - "--providers.docker=true"
      - "--providers.docker.network=traefik"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.middlewares=secure-https@file"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.le-tls.acme.tlsChallenge=true"
      - "--certificatesresolvers.le-tls.acme.email={{ general_mail_admin }}@{{ general_domain_default }}"
      - "--certificatesresolvers.le-tls.acme.storage=/letsencrypt/acme.json"
      - "--api=true"
      - "--ping.manualrouting=true"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik
    volumes:
      - "./traefik:/conf"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik-cert:/letsencrypt/"
    environment:
      - "TZ={{ general_timezone }}"

  # =========================
  # =          DDNS         =
  # =========================
  ddclient:
    <<: *defaults
    image: ghcr.io/linuxserver/ddclient
    container_name: ddclient
    environment:
      - "TZ={{ general_timezone }}"
    volumes:
      - ./ddclient:/config

  # =========================
  # =        TORRENT        =
  # =========================
  transmission:
    <<: *defaults
    image: linuxserver/transmission:latest
    container_name: transmission
    networks:
      - traefik
    ports:
      - "51413:51413"
      - "51413:51413/udp"
    environment:
      - "TZ={{ general_timezone }}"
      - "PUID=233"
      - "PGID=233"
      - "TRANSMISSION_WEB_HOME=/combustion-release/"
      - "USER={{ app_transmission_user }}"
      - "PASS={{ app_transmission_password }}"
    volumes:
      - "/media/data/services/transmission/:/downloads/incomplete"
      - "/media/data/media/000. Plex/Nazien:/downloads/complete"
      - "{{ general_path_appdata }}/transmission:/config"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.entrypoints=websecure"
      - "traefik.http.routers.transmission.rule=Host(`torrent.{{ general_domain_default }}`)"
      - "traefik.http.routers.transmission.tls.certresolver=le-tls"
      - "traefik.http.services.transmission-{{ ansible_hostname }}.loadbalancer.server.port=9091"

  # =========================
  # =         SAMBA         =
  # =========================
  samba:
    <<: *defaults
    image: dperson/samba:latest
    container_name: samba
    ports:
      - "{{ machine_local_ip }}:139:139"
      - "{{ machine_local_ip }}:445:445"
    volumes:
      - "/media/data/media:/mnt/media"
    environment:
      - "TZ={{ general_timezone }}"
      - "USERID=233"
      - "GROUPID=233"
    command: >
      samba.sh -S
      -u "nas;{{ app_samba_nas_password }}"
      -u "scanner;{{ app_samba_scanner_password }}"
      -s "media;/mnt/media;yes;no;no;nas"
      -s "scans;/mnt/media/Scans;yes;no;no;scanner"

  # =========================
  # =          PLEX         =
  # =========================
  plex:
    <<: *defaults
    image: plexinc/pms-docker:latest
    container_name: plex
    network_mode: "host"
    volumes:
      - "/media/data/media/000. Plex:/data/media"
      - "/media/data/services/plex/optimized:/data/optimized"
      - "{{ general_path_appdata }}/plex/config:/config"
      - "{{ general_path_appdata }}/plex/transcode:/transcode"
    devices:
      - "/dev/dri/card0:/dev/dri/card0"
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    environment:
      - "TZ={{ general_timezone }}"
      - "PLEX_UID=233"
      - "PLEX_GID=233"

  # =========================
  # =   TINY MEDIA MANAGER  =
  # =========================
  tmm:
    <<: *defaults
    image: romancin/tinymediamanager:latest
    container_name: tmm
    networks:
      - traefik
    volumes:
      - "/media/data/media/000. Plex:/media"
      - "{{ general_path_appdata }}/tmm/config:/config"
    environment:
      - "TZ={{ general_timezone }}"
      - "GROUP_ID=0"
      - "USER_ID=0"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tmm.entrypoints=websecure"
      - "traefik.http.routers.tmm.rule=Host(`tmm.{{ general_domain_default }}`)"
      - "traefik.http.routers.tmm.tls.certresolver=le-tls"
      - "traefik.http.routers.tmm.middlewares=tmm-auth@file"
      - "traefik.http.services.tmm-{{ ansible_hostname }}.loadbalancer.server.port=5800"

  # =========================
  # =       SYNCTHING       =
  # =========================
  syncthing:
    <<: *defaults
    image: syncthing/syncthing:1
    container_name: syncthing
    networks:
      - traefik
    ports:
      - "22000:22000"
    volumes:
      - "{{ general_path_appdata }}/syncthing/config:/var/syncthing"
      - "/media/data/media/000. Plex/Music:/data/music"
    environment:
      - "TZ={{ general_timezone }}"
      - "PUID=233"
      - "PGID=233"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.entrypoints=websecure"
      - "traefik.http.routers.syncthing.rule=Host(`syncthing-{{ ansible_hostname }}.{{ general_domain_default }}`)"
      - "traefik.http.routers.syncthing.tls.certresolver=le-tls"
      - "traefik.http.services.syncthing-{{ ansible_hostname }}.loadbalancer.server.port=8384"

  # =========================
  # =        LOGGING        =
  # =========================
  promtail:
    <<: *defaults
    image: grafana/promtail:2.2.0
    container_name: promtail
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
      - promtail-positions:/positions
      - /var/log:/var/log:ro
    environment:
      - "TZ={{ general_timezone }}"

  # =========================
  # =         BACKUP        =
  # =========================
  borgmatic:
    <<: *defaults
    image: b3vis/borgmatic:latest
    container_name: borgmatic
    privileged: true # Required for borg mount
    cap_add:
      - SYS_ADMIN # Required for borg mount
    volumes:
      # Backup locations
      - "/media/data/media/000. Plex/Photos:/mnt/source/plex/photos:ro"
      - "/media/data/media/000. Plex/Music:/mnt/source/plex/music:ro"
      # Config and cache
      - "./borgmatic/borgmatic.d:/etc/borgmatic.d"
      - "./borgmatic/ssh:/root/.ssh"
      - "{{ general_path_appdata }}/borgmatic/config:/root/.config/borg"
      - "{{ general_path_appdata }}/borgmatic/cache:/root/.cache/borg"
      - "{{ general_path_appdata }}/borgmatic/restore:/mnt/restore"
    devices:
      - "/dev/fuse:/dev/fuse" # Required for borg mount
    environment:
      - "TZ={{ general_timezone }}"
      - "BORG_PASSPHRASE={{ app_borgmatic_borg_passphrase }}"

# #################################################################
# #                            VOLUMES                            #
# #################################################################
volumes:
  promtail-positions:
  traefik-cert:

# #################################################################
# #                            NETWORKS                           #
# #################################################################
networks:
  traefik:
    name: traefik
