# yaml-language-server: $schema=https://json.schemastore.org/any.json

apiVersion: 1

# Marks provisioned data sources for deletion if they are no longer in a provisioning file.
prune: true

datasources:
  - uid: ds_prometheus_main
    name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
