# yaml-language-server: $schema=https://json.schemastore.org/any.json

apiVersion: 1
datasources:
  - uid: ds_prometheus
    name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
