- name: Setup logging to Graylog
  become: true
  tags: ["setup", "logging"]
  block:
    - name: Install filebeat
      ansible.builtin.apt:
        deb: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.14.3-{{ arch }}.deb"

    - name: Copy filebeat config
      register: filebeat_config
      ansible.builtin.template:
        src: filebeat.yml
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: "600"
        block_start_string: "#BLOCK:"
        block_end_string: ":BLOCK#"
        variable_start_string: "#VAR:"
        variable_end_string: ":VAR#"
      notify: Restart filebeat

    - name: Ensure filebeat is started and enabled
      ansible.builtin.service:
        name: filebeat
        state: started
        enabled: true
