- name: Copy systemd system unit templates
  include_tasks: tasks/helpers/copy_templates_folder.yml
  vars:
    - templates_folder: "{{ ansible_hostname }}/etc/systemd/system"
    - destination_folder: "/etc/systemd/system"
    - destination_owner: root
    - destination_group: root
    - destination_mode_files: 0600
    - destination_mode_dirs: 0700
    - destination_delete_extra: false
  tags: ["systemd"]

- name: Force systemd reload
  become: yes
  systemd:
    daemon_reload: yes
  tags: ["systemd"]

- name: Enable systemd services and timers
  become: yes
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - bjoetiek-dump-db.timer
    - docker-update-containers.timer
    - isa-rclone.timer
    - nextcloud-calcardbackup.timer
    - nextcloud-cron.timer
    - nextcloud-dump-db.timer
    - nextcloud-preview-generator.timer
    - nextcloud-update-apps.timer
    - passit-dump-db.timer
    - snipe-it-dump-db.timer
  tags: ["systemd"]

- name: Copy home/_user_/eve templates
  include_tasks: tasks/helpers/copy_templates_folder.yml
  vars:
    - templates_folder: "{{ ansible_hostname }}/home/_user_/eve"
    - destination_folder: "{{ ansible_user_dir }}/{{ ansible_hostname }}"
    - destination_owner: "{{ ansible_real_user_id }}"
    - destination_group: "{{ ansible_real_group_id }}"
    - destination_mode_files: 0600
    - destination_mode_dirs: 0700
    - destination_delete_extra: true
  tags: ["docker"]
