- include_tasks: tasks/powertop.yml
  tags: ["setup", "powertop"]

- name: Copy Netplan config
  become: yes
  ansible.builtin.copy:
    src: "{{ ansible_hostname }}/netplan.yaml"
    dest: "/etc/netplan/00-installer-config.yaml"
    owner: root
    group: root
    mode: "0644"
  tags: ["config"]

- name: Set grub option intel_idle.max_cstate to fix freezing
  become: yes
  register: grub_config
  ansible.builtin.lineinfile:
    state: present
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX="
    line: 'GRUB_CMDLINE_LINUX="intel_idle.max_cstate=1"'
  tags: ["config"]

- name: Update grub if config changed
  become: yes
  when: grub_config.changed
  ansible.builtin.command: "update-grub"
  tags: ["config"]

- name: Copy systemd system unit templates
  include_tasks: tasks/helpers/copy_templates_folder.yml
  vars:
    - templates_folder: "{{ ansible_hostname }}/etc/systemd/system"
    - destination_folder: "/etc/systemd/system"
    - destination_owner: root
    - destination_group: root
    - destination_mode_files: 0600
    - destination_mode_dirs: 0700
    - destination_delete_extra: false
  tags: ["systemd"]

- name: Force systemd reload
  become: yes
  systemd:
    daemon_reload: yes
  tags: ["systemd"]

- name: Enable systemd services and timers
  become: yes
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - btrfs-scrub.timer
    - docker-update-containers.timer
    - media-backup.mount
    - media-data.mount
  tags: ["systemd"]

- name: Copy home/_user_/olaf templates
  include_tasks: tasks/helpers/copy_templates_folder.yml
  vars:
    - templates_folder: "{{ ansible_hostname }}/home/_user_/olaf"
    - destination_folder: "{{ ansible_user_dir }}/{{ ansible_hostname }}"
    - destination_owner: "{{ ansible_real_user_id }}"
    - destination_group: "{{ ansible_real_group_id }}"
    - destination_mode_files: 0600
    - destination_mode_dirs: 0700
    - destination_delete_extra: true
  tags: ["docker"]
